// app/dashboard/admin/orders/data.ts
import { Order } from "./types";

export const MOCK_ALL_ORDERS: Order[] = [
  {
    id: "1",
    orderId: "ORD-2025-001",
    customerName: "Saman Kumara",
    shopName: "Saman Electronics",
    date: "2025-02-20",
    totalAmount: 15400,
    itemCount: 12,
    status: "Pending",
    paymentStatus: "Unpaid",
    salesRep: "Ajith Bandara",
  },
  {
    id: "2",
    orderId: "ORD-2025-002",
    customerName: "Nimal Perera",
    shopName: "City Hardware",
    date: "2025-02-19",
    totalAmount: 85000,
    itemCount: 45,
    status: "Processing",
    paymentStatus: "Unpaid",
    salesRep: "Chathura Perera",
  },
  {
    id: "3",
    orderId: "ORD-2025-003",
    customerName: "Kamal Silva",
    shopName: "Lanka Traders",
    date: "2025-02-19",
    totalAmount: 24500,
    itemCount: 8,
    status: "Checking",
    paymentStatus: "Unpaid",
    salesRep: "Dilshan Silva",
  },
  {
    id: "4",
    orderId: "ORD-2025-004",
    customerName: "Sunil Das",
    shopName: "Ruhuna Motors",
    date: "2025-02-18",
    totalAmount: 120000,
    itemCount: 60,
    status: "Loading",
    paymentStatus: "Partial",
    salesRep: "Ajith Bandara",
  },
  {
    id: "5",
    orderId: "ORD-2025-005",
    customerName: "Mahesh",
    shopName: "Global Paints",
    date: "2025-02-18",
    totalAmount: 45000,
    itemCount: 22,
    status: "Delivered",
    paymentStatus: "Paid",
    salesRep: "Chathura Perera",
  },
  {
    id: "6",
    orderId: "ORD-2025-006",
    customerName: "Kasun Rajitha",
    shopName: "K.R. Stores",
    date: "2025-02-20",
    totalAmount: 32000,
    itemCount: 15,
    status: "Pending",
    paymentStatus: "Unpaid",
    salesRep: "Dilshan Silva",
  },
];